defmodule Gamend.ClientLogs.Session do
  @moduledoc """
  One run of the game on one device, as seen from the server.

  Holds no log lines. The lines go to `Logger` and out to the host's log store;
  this is the index that makes them findable — who, which build, which lobbies,
  how many errors. See `Gamend.ClientLogs`.

  `client_session_id` is generated by the client (it has to name the session
  before it can reach us) and is bound to an owner on first write, so a second
  device claiming the same id is rejected rather than allowed to write into
  someone else's timeline.
  """

  use Gamend.Schema
  import Ecto.Changeset

  @type t :: %__MODULE__{}

  @platforms ~w(android ios web windows macos linux unknown)
  @builds ~w(debug release)

  @string_max 128

  schema "client_sessions" do
    field :client_session_id, :string
    field :device_id, :string, default: ""
    field :platform, :string, default: "unknown"
    field :app_version, :string, default: ""
    field :build, :string, default: "release"
    field :locale, :string, default: ""

    field :started_at, :utc_datetime_usec
    field :last_seen_at, :utc_datetime_usec

    field :entry_count, :integer, default: 0
    field :warn_count, :integer, default: 0
    field :error_count, :integer, default: 0
    field :dropped_count, :integer, default: 0
    field :max_seq, :integer, default: 0

    field :flagged, :boolean, default: false
    field :meta, :map, default: %{}

    belongs_to :user, Gamend.Accounts.User

    timestamps(type: :utc_datetime_usec)
  end

  @spec platforms() :: [String.t()]
  def platforms, do: @platforms

  @spec builds() :: [String.t()]
  def builds, do: @builds

  @doc """
  Changeset for the first write of a session. Later batches update counters
  through `Gamend.ClientLogs`, not through here.
  """
  @spec changeset(t(), map()) :: Ecto.Changeset.t()
  def changeset(session, attrs) do
    session
    |> cast(attrs, [
      :client_session_id,
      :user_id,
      :device_id,
      :platform,
      :app_version,
      :build,
      :locale,
      :started_at,
      :last_seen_at,
      :meta
    ])
    |> validate_required([:client_session_id, :started_at, :last_seen_at])
    |> validate_length(:client_session_id, min: 8, max: @string_max)
    |> validate_length(:device_id, max: @string_max)
    |> validate_length(:app_version, max: @string_max)
    |> validate_length(:locale, max: @string_max)
    |> validate_inclusion(:platform, @platforms)
    |> validate_inclusion(:build, @builds)
    |> unique_constraint(:client_session_id)
    |> foreign_key_constraint(:user_id)
  end
end
